### ISSUE TITLE
Decrypter

### ISSUE THREAD

**Issue by Angelokh22** [Fvted/TikTok-Login-Encryption#1]
Thanks a lot for this encryption.
I've been searching for this encryption algorithm.

Soo....
Can you inverse it so we can decrypt encrypted media???

**Comment by eeetorres** [comment]
Hi, thanks for the suggestion!
Here is an example of what it would look like inversed:
```py
def decrypt(string):
    decrypted = []
    for i in range(0, len(string), 2):
        current = bytearray.fromhex(string[i:i+2]).decode()
        current = 5 ^ ord(current)
        decrypted.append(chr(current))
    return "".join(decrypted)
